#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
 #define REVISION_DB_CHARACTERS "required_12712_01_characters_characters"
 #define REVISION_DB_MANGOS "required_12752_01_mangos_reputation_spillover_template"
#define REVISION_DB_REALMD "required_20150722_01_realmcharacters_remove_constraint"
#endif // __REVISION_SQL_H__
